// Structured data for Projects and Gallery pages
// This file is auto-generated by extract_and_download.py

export const youtubeProjects = [
  {
    "id": "aEyFnoHDUuo",
    "title": "2 Bhk Traditional Home I Budget Home I Evoor Project IDone by Innovate Designers &amp; Builders Pvt Ltd",
    "category": "Budget Home",
    "thumbnail": "https://img.youtube.com/vi/aEyFnoHDUuo/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=aEyFnoHDUuo"
  },
  {
    "id": "aqo3Vx1eGKE",
    "title": "4 Bhk Budget Home Construction I Pallickal",
    "category": "Budget Home",
    "thumbnail": "https://img.youtube.com/vi/aqo3Vx1eGKE/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=aqo3Vx1eGKE"
  },
  {
    "id": "iRhEn6iGoUk",
    "title": "4 Bhk Budget Home Construction I Edathuva I 24.30 Lakhs Construction Cost",
    "category": "Budget Home",
    "thumbnail": "https://img.youtube.com/vi/iRhEn6iGoUk/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=iRhEn6iGoUk"
  },
  {
    "id": "KVzRPICWrqg",
    "title": "4 Bhk Budget Home Construction 30 LakhsIHaripad",
    "category": "Budget Home",
    "thumbnail": "https://img.youtube.com/vi/KVzRPICWrqg/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=KVzRPICWrqg"
  },
  {
    "id": "L0sAmtfghxM",
    "title": "3 Bhk Budget Home Construction I Budget Home I Palliruthy Ernakulam I Done by Innovate Builders",
    "category": "Budget Home",
    "thumbnail": "https://img.youtube.com/vi/L0sAmtfghxM/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=L0sAmtfghxM"
  },
  {
    "id": "M1h0MHWWaF4",
    "title": "4 Bhk Budget Home Construction I Kuttanad Home",
    "category": "Budget Home",
    "thumbnail": "https://img.youtube.com/vi/M1h0MHWWaF4/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=M1h0MHWWaF4"
  },
  {
    "id": "RrtIgladLL8",
    "title": "4bhk Budget Home I Construction I 26 Lakhs I Innovate Builders",
    "category": "Budget Home",
    "thumbnail": "https://img.youtube.com/vi/RrtIgladLL8/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=RrtIgladLL8"
  },
  {
    "id": "SwEVIpbdT98",
    "title": "3 Bhk Budget Home Construction I Athirampuzha I Done By Innovate Designers &amp; Builders Pvt Ltd",
    "category": "Budget Home",
    "thumbnail": "https://img.youtube.com/vi/SwEVIpbdT98/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=SwEVIpbdT98"
  },
  {
    "id": "W5sl3_VIubc",
    "title": "4 Bhk Home Construction I Budget Home I Cheppad I done by innovate designers &amp; Builders Pvt Ltd",
    "category": "Budget Home",
    "thumbnail": "https://img.youtube.com/vi/W5sl3_VIubc/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=W5sl3_VIubc"
  },
  {
    "id": "Za062wxUZQM",
    "title": "3 Bhk Home Construction I Budget Home I Vaikom  I Done by Innovate Builders Pvt Ltd",
    "category": "Budget Home",
    "thumbnail": "https://img.youtube.com/vi/Za062wxUZQM/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=Za062wxUZQM"
  },
  {
    "id": "66E81eEDYlY",
    "title": "4 Bhk Home I Economical Home I Cherthala I Done by Innovate Builders Pvt Ltd",
    "category": "Economical Home",
    "thumbnail": "https://img.youtube.com/vi/66E81eEDYlY/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=66E81eEDYlY"
  },
  {
    "id": "74NFgiApHtA",
    "title": "3 Bhk Home Construction Economical Home I Thankasserry I Done By Innovate Designers &amp; Builders",
    "category": "Economical Home",
    "thumbnail": "https://img.youtube.com/vi/74NFgiApHtA/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=74NFgiApHtA"
  },
  {
    "id": "9dGOXvsz6To",
    "title": "5 Bhk Home  Economical Home design  Karukachal Project",
    "category": "Economical Home",
    "thumbnail": "https://img.youtube.com/vi/9dGOXvsz6To/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=9dGOXvsz6To"
  },
  {
    "id": "9P0ehjdc3S4",
    "title": "5 Bhk Economical Residential Home I Karikkakam Project",
    "category": "Economical Home",
    "thumbnail": "https://img.youtube.com/vi/9P0ehjdc3S4/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=9P0ehjdc3S4"
  },
  {
    "id": "aIRYdjp9Mkg",
    "title": "4 Bhk Home Construction I Economical Home I Anchalmoodu Kollam I Done by Innovate Builders",
    "category": "Economical Home",
    "thumbnail": "https://img.youtube.com/vi/aIRYdjp9Mkg/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=aIRYdjp9Mkg"
  },
  {
    "id": "CYqnGsXkjRA",
    "title": "4 bhk Home Construction economical I Charumoodu#Aalappuzha I done by Innovate Designers &amp; Builders",
    "category": "Economical Home",
    "thumbnail": "https://img.youtube.com/vi/CYqnGsXkjRA/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=CYqnGsXkjRA"
  },
  {
    "id": "FQcihhMBAh0",
    "title": "4 Bhk Residential Home I 2277 Sqft I Pala Proejct",
    "category": "Economical Home",
    "thumbnail": "https://img.youtube.com/vi/FQcihhMBAh0/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=FQcihhMBAh0"
  },
  {
    "id": "gFXOzkQzFPk",
    "title": "4 Bhk Economical Home I Construction I 1925 Sqft I Home Design",
    "category": "Economical Home",
    "thumbnail": "https://img.youtube.com/vi/gFXOzkQzFPk/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=gFXOzkQzFPk"
  },
  {
    "id": "w0YwYRRRAck",
    "title": "5 Bhk Residentail Economical Home I 1964 Sqft I 5 Bhk Home",
    "category": "Economical Home",
    "thumbnail": "https://img.youtube.com/vi/w0YwYRRRAck/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=w0YwYRRRAck"
  },
  {
    "id": "YLULOQ5qL-4",
    "title": "4 bhk Home Construction economical Home Sreekaryam I done by Innovate Designers &amp; Builders Pvt Ltd",
    "category": "Economical Home",
    "thumbnail": "https://img.youtube.com/vi/YLULOQ5qL-4/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=YLULOQ5qL-4"
  },
  {
    "id": "AzTLSBFzFo8",
    "title": "3 Bhk Home Construction I Home Design I Semi Economical",
    "category": "Semi Economical Home",
    "thumbnail": "https://img.youtube.com/vi/AzTLSBFzFo8/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=AzTLSBFzFo8"
  },
  {
    "id": "KvejVVdXC8Q",
    "title": "Innovate Builders Balaramapuram Project",
    "category": "Semi Economical Home",
    "thumbnail": "https://img.youtube.com/vi/KvejVVdXC8Q/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=KvejVVdXC8Q"
  },
  {
    "id": "Q1kNmcvH8e8",
    "title": "4 Bhk Home I 34.5 Lakhs I Semi Economical Residential Home I Full Project Video",
    "category": "Semi Economical Home",
    "thumbnail": "https://img.youtube.com/vi/Q1kNmcvH8e8/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=Q1kNmcvH8e8"
  },
  {
    "id": "UUw7_20EPQg",
    "title": "4 Bhk Construction Semi Economical Design I Mangad I Kollam",
    "category": "Semi Economical Home",
    "thumbnail": "https://img.youtube.com/vi/UUw7_20EPQg/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=UUw7_20EPQg"
  },
  {
    "id": "ew7YvZGJABs",
    "title": "4 Bhk Home Construction Luxury Home I Piravom I Done by Innovate Designers &amp; Builders Pvt Ltd",
    "category": "Luxury Home",
    "thumbnail": "https://img.youtube.com/vi/ew7YvZGJABs/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=ew7YvZGJABs"
  },
  {
    "id": "ZIEY6n7mnSs",
    "title": "3 Bhk Luxury Construction I Home Design Done Innovate Builders",
    "category": "Luxury Home",
    "thumbnail": "https://img.youtube.com/vi/ZIEY6n7mnSs/hqdefault.jpg",
    "youtubeUrl": "https://www.youtube.com/watch?v=ZIEY6n7mnSs"
  }
];

export const galleryCategories = {
  "box-type": [
    {
      "title": "Innovate Builders Box Type Elevation 1 1024X555",
      "src": "/assets/images/box-type/innovate-builders-box-type-elevation-1-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Box Type Elevation 10 1024X555",
      "src": "/assets/images/box-type/innovate-builders-box-type-elevation-10-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Box Type Elevation 11 1024X555",
      "src": "/assets/images/box-type/innovate-builders-box-type-elevation-11-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Box Type Elevation 12 1024X555",
      "src": "/assets/images/box-type/innovate-builders-box-type-elevation-12-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Box Type Elevation 13 1024X555",
      "src": "/assets/images/box-type/innovate-builders-box-type-elevation-13-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Box Type Elevation 14 1024X555",
      "src": "/assets/images/box-type/innovate-builders-box-type-elevation-14-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Box Type Elevation 15 1024X555",
      "src": "/assets/images/box-type/innovate-builders-box-type-elevation-15-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Box Type Elevation 16 1024X555",
      "src": "/assets/images/box-type/innovate-builders-box-type-elevation-16-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Box Type Elevation 17 1024X555",
      "src": "/assets/images/box-type/innovate-builders-box-type-elevation-17-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Box Type Elevation 18 1024X555",
      "src": "/assets/images/box-type/innovate-builders-box-type-elevation-18-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Box Type Elevation 19 1024X555",
      "src": "/assets/images/box-type/innovate-builders-box-type-elevation-19-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Box Type Elevation 2 1024X555",
      "src": "/assets/images/box-type/innovate-builders-box-type-elevation-2-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Box Type Elevation 20 1024X555",
      "src": "/assets/images/box-type/innovate-builders-box-type-elevation-20-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Box Type Elevation 3 1024X555",
      "src": "/assets/images/box-type/innovate-builders-box-type-elevation-3-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Box Type Elevation 4 1024X555",
      "src": "/assets/images/box-type/innovate-builders-box-type-elevation-4-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Box Type Elevation 5 1024X555",
      "src": "/assets/images/box-type/innovate-builders-box-type-elevation-5-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Box Type Elevation 6 1024X555",
      "src": "/assets/images/box-type/innovate-builders-box-type-elevation-6-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Box Type Elevation 7 1024X555",
      "src": "/assets/images/box-type/innovate-builders-box-type-elevation-7-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Box Type Elevation 8 1024X555",
      "src": "/assets/images/box-type/innovate-builders-box-type-elevation-8-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Box Type Elevation 9 1024X555",
      "src": "/assets/images/box-type/innovate-builders-box-type-elevation-9-1024x555.jpg"
    }
  ],
  "colonial": [
    {
      "title": "Innovate Builders Colonial Type Elevation 1 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-1-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Colonial Type Elevation 10 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-10-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Colonial Type Elevation 11 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-11-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Colonial Type Elevation 12 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-12-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Colonial Type Elevation 13 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-13-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Colonial Type Elevation 14 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-14-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Colonial Type Elevation 15 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-15-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Colonial Type Elevation 16 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-16-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Colonial Type Elevation 17 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-17-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Colonial Type Elevation 18 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-18-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Colonial Type Elevation 19 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-19-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Colonial Type Elevation 2 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-2-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Colonial Type Elevation 20 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-20-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Colonial Type Elevation 21 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-21-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Colonial Type Elevation 22 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-22-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Colonial Type Elevation 3 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-3-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Colonial Type Elevation 4 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-4-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Colonial Type Elevation 5 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-5-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Colonial Type Elevation 6 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-6-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Colonial Type Elevation 7 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-7-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Colonial Type Elevation 8 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-8-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Colonial Type Elevation 9 1024X555",
      "src": "/assets/images/colonial/innovate-builders-colonial-type-elevation-9-1024x555.jpg"
    }
  ],
  "contemporary": [
    {
      "title": "Innovate Builders Contemporary House Home Elevation 1 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-1-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 10 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-10-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 11 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-11-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 12 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-12-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 13 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-13-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 14 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-14-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 15 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-15-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 16 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-16-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 17 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-17-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 18 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-18-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 19 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-19-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 2 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-2-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 20 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-20-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 21 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-21-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 22 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-22-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 23 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-23-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 24 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-24-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 25 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-25-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 26 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-26-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 27 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-27-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 3 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-3-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 4 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-4-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 5 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-5-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 6 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-6-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 7 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-7-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 8 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-8-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Contemporary House Home Elevation 9 1024X555",
      "src": "/assets/images/contemporary/innovate-builders-contemporary-house-home-elevation-9-1024x555.jpg"
    }
  ],
  "curved-roof": [
    {
      "title": "Innovate Builders Home House Curved Roof Elevation 1 1024X555",
      "src": "/assets/images/curved-roof/innovate-builders-home-house-curved-roof-elevation-1-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home House Curved Roof Elevation 11 1024X555",
      "src": "/assets/images/curved-roof/innovate-builders-home-house-curved-roof-elevation-11-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home House Curved Roof Elevation 12 1024X555",
      "src": "/assets/images/curved-roof/innovate-builders-home-house-curved-roof-elevation-12-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home House Curved Roof Elevation 13 1024X555",
      "src": "/assets/images/curved-roof/innovate-builders-home-house-curved-roof-elevation-13-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home House Curved Roof Elevation 14 1024X555",
      "src": "/assets/images/curved-roof/innovate-builders-home-house-curved-roof-elevation-14-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home House Curved Roof Elevation 15 1024X555",
      "src": "/assets/images/curved-roof/innovate-builders-home-house-curved-roof-elevation-15-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home House Curved Roof Elevation 2 1024X555",
      "src": "/assets/images/curved-roof/innovate-builders-home-house-curved-roof-elevation-2-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home House Curved Roof Elevation 3 1024X555",
      "src": "/assets/images/curved-roof/innovate-builders-home-house-curved-roof-elevation-3-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home House Curved Roof Elevation 4 1024X555",
      "src": "/assets/images/curved-roof/innovate-builders-home-house-curved-roof-elevation-4-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home House Curved Roof Elevation 5 1024X555",
      "src": "/assets/images/curved-roof/innovate-builders-home-house-curved-roof-elevation-5-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home House Curved Roof Elevation 6 1024X555",
      "src": "/assets/images/curved-roof/innovate-builders-home-house-curved-roof-elevation-6-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home House Curved Roof Elevation 7 1024X555",
      "src": "/assets/images/curved-roof/innovate-builders-home-house-curved-roof-elevation-7-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home House Curved Roof Elevation 8 1024X555",
      "src": "/assets/images/curved-roof/innovate-builders-home-house-curved-roof-elevation-8-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home House Curved Roof Elevation 9 1024X555",
      "src": "/assets/images/curved-roof/innovate-builders-home-house-curved-roof-elevation-9-1024x555.jpg"
    }
  ],
  "traditional-contemporary": [
    {
      "title": "Innovate Builders Traditional Contemporary Mix Elevation 1 1024X555",
      "src": "/assets/images/traditional-contemporary/innovate-builders-traditional-contemporary-mix-elevation-1-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Traditional Contemporary Mix Elevation 2 1024X555",
      "src": "/assets/images/traditional-contemporary/innovate-builders-traditional-contemporary-mix-elevation-2-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Traditional Contemporary Mix Elevation 3 1024X555",
      "src": "/assets/images/traditional-contemporary/innovate-builders-traditional-contemporary-mix-elevation-3-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Traditional Contemporary Mix Elevation 4 1024X555",
      "src": "/assets/images/traditional-contemporary/innovate-builders-traditional-contemporary-mix-elevation-4-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Traditional Contemporary Mix Elevation 5 1024X555",
      "src": "/assets/images/traditional-contemporary/innovate-builders-traditional-contemporary-mix-elevation-5-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Traditional Contemporary Mix Elevation 6 1024X555",
      "src": "/assets/images/traditional-contemporary/innovate-builders-traditional-contemporary-mix-elevation-6-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Traditional Contemporary Mix Elevation 7 1024X555",
      "src": "/assets/images/traditional-contemporary/innovate-builders-traditional-contemporary-mix-elevation-7-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Traditional Contemporary Mix Elevation 8 1024X555",
      "src": "/assets/images/traditional-contemporary/innovate-builders-traditional-contemporary-mix-elevation-8-1024x555.jpg"
    }
  ],
  "western-type": [
    {
      "title": "Innovate Builders Home House Western Elevation 1 1024X555",
      "src": "/assets/images/western-type/innovate-builders-home-house-western-elevation-1-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home House Western Elevation 2 1024X555",
      "src": "/assets/images/western-type/innovate-builders-home-house-western-elevation-2-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home House Western Elevation 3 1024X555",
      "src": "/assets/images/western-type/innovate-builders-home-house-western-elevation-3-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home House Western Elevation 4 1024X555",
      "src": "/assets/images/western-type/innovate-builders-home-house-western-elevation-4-1024x555.jpg"
    }
  ],
  "single-storey": [
    {
      "title": "Innovate Builders Home Single Storey House Elevation 1 1 1024X555",
      "src": "/assets/images/single-storey/innovate-builders-home-single-storey-house-elevation-1-1-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home Single Storey House Elevation 10 1024X555",
      "src": "/assets/images/single-storey/innovate-builders-home-single-storey-house-elevation-10-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home Single Storey House Elevation 11 1024X555",
      "src": "/assets/images/single-storey/innovate-builders-home-single-storey-house-elevation-11-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home Single Storey House Elevation 12 1024X555",
      "src": "/assets/images/single-storey/innovate-builders-home-single-storey-house-elevation-12-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home Single Storey House Elevation 13 1024X555",
      "src": "/assets/images/single-storey/innovate-builders-home-single-storey-house-elevation-13-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home Single Storey House Elevation 2 1024X555",
      "src": "/assets/images/single-storey/innovate-builders-home-single-storey-house-elevation-2-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home Single Storey House Elevation 3 1024X555",
      "src": "/assets/images/single-storey/innovate-builders-home-single-storey-house-elevation-3-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home Single Storey House Elevation 4 1024X555",
      "src": "/assets/images/single-storey/innovate-builders-home-single-storey-house-elevation-4-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home Single Storey House Elevation 5 1024X555",
      "src": "/assets/images/single-storey/innovate-builders-home-single-storey-house-elevation-5-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home Single Storey House Elevation 6 1024X555",
      "src": "/assets/images/single-storey/innovate-builders-home-single-storey-house-elevation-6-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home Single Storey House Elevation 7 1024X555",
      "src": "/assets/images/single-storey/innovate-builders-home-single-storey-house-elevation-7-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home Single Storey House Elevation 8 1024X555",
      "src": "/assets/images/single-storey/innovate-builders-home-single-storey-house-elevation-8-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Home Single Storey House Elevation 9 1024X555",
      "src": "/assets/images/single-storey/innovate-builders-home-single-storey-house-elevation-9-1024x555.jpg"
    }
  ],
  "interior": [
    {
      "title": "Innovate Builders Bedroom Interior Designing 1 1024X555",
      "src": "/assets/images/interior/innovate-builders-bedroom-Interior-designing-1-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Bedroom Interior Designing 10 1024X555",
      "src": "/assets/images/interior/innovate-builders-bedroom-Interior-designing-10-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Bedroom Interior Designing 11 1024X555",
      "src": "/assets/images/interior/innovate-builders-bedroom-Interior-designing-11-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Bedroom Interior Designing 2 1024X555",
      "src": "/assets/images/interior/innovate-builders-bedroom-Interior-designing-2-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Bedroom Interior Designing 3 1024X555",
      "src": "/assets/images/interior/innovate-builders-bedroom-Interior-designing-3-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Bedroom Interior Designing 4 1024X555",
      "src": "/assets/images/interior/innovate-builders-bedroom-Interior-designing-4-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Bedroom Interior Designing 5 1024X555",
      "src": "/assets/images/interior/innovate-builders-bedroom-Interior-designing-5-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Bedroom Interior Designing 6 1024X555",
      "src": "/assets/images/interior/innovate-builders-bedroom-Interior-designing-6-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Bedroom Interior Designing 7 1024X555",
      "src": "/assets/images/interior/innovate-builders-bedroom-Interior-designing-7-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Bedroom Interior Designing 8 1024X555",
      "src": "/assets/images/interior/innovate-builders-bedroom-Interior-designing-8-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Bedroom Interior Designing 9 1024X555",
      "src": "/assets/images/interior/innovate-builders-bedroom-Interior-designing-9-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Courtyard Interior Designing 1 1024X555",
      "src": "/assets/images/interior/innovate-builders-courtyard-interior-designing-1-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Courtyard Interior Designing 2 1024X555",
      "src": "/assets/images/interior/innovate-builders-courtyard-interior-designing-2-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Courtyard Interior Designing 3 1024X555",
      "src": "/assets/images/interior/innovate-builders-courtyard-interior-designing-3-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Courtyard Interior Designing 4 1024X555",
      "src": "/assets/images/interior/innovate-builders-courtyard-interior-designing-4-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Dining Interior Designing 1 1024X555",
      "src": "/assets/images/interior/innovate-builders-dining-interior-designing-1-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Dining Interior Designing 2 1024X555",
      "src": "/assets/images/interior/innovate-builders-dining-interior-designing-2-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Dining Interior Designing 3 1024X555",
      "src": "/assets/images/interior/innovate-builders-dining-interior-designing-3-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Dining Interior Designing 4 1024X555",
      "src": "/assets/images/interior/innovate-builders-dining-interior-designing-4-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Dining Interior Designing 5 1024X555",
      "src": "/assets/images/interior/innovate-builders-dining-interior-designing-5-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Dining Interior Designing 6 1024X555",
      "src": "/assets/images/interior/innovate-builders-dining-interior-designing-6-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Dining Interior Designing 7 1024X555",
      "src": "/assets/images/interior/innovate-builders-dining-interior-designing-7-1024x555.jpg"
    },
    {
      "title": "Innovate Builders First Floor Living Interior Designing 1 1024X555",
      "src": "/assets/images/interior/innovate-builders-first-floor-living-interior-designing-1-1024x555.jpg"
    },
    {
      "title": "Innovate Builders First Floor Living Interior Designing 2 1024X555",
      "src": "/assets/images/interior/innovate-builders-first-floor-living-interior-designing-2-1024x555.jpg"
    },
    {
      "title": "Innovate Builders First Floor Living Interior Designing 3 1024X555",
      "src": "/assets/images/interior/innovate-builders-first-floor-living-interior-designing-3-1024x555.jpg"
    },
    {
      "title": "Innovate Builders First Floor Living Interior Designing 4 1024X555",
      "src": "/assets/images/interior/innovate-builders-first-floor-living-interior-designing-4-1024x555.jpg"
    },
    {
      "title": "Innovate Builders First Floor Living Interior Designing 5 1024X555",
      "src": "/assets/images/interior/innovate-builders-first-floor-living-interior-designing-5-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Ground Floor Living Interior Designing 1 1024X555",
      "src": "/assets/images/interior/innovate-builders-ground-floor-living-interior-designing-1-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Ground Floor Living Interior Designing 10 1024X555",
      "src": "/assets/images/interior/innovate-builders-ground-floor-living-interior-designing-10-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Ground Floor Living Interior Designing 11 1024X555",
      "src": "/assets/images/interior/innovate-builders-ground-floor-living-interior-designing-11-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Ground Floor Living Interior Designing 12 1024X555",
      "src": "/assets/images/interior/innovate-builders-ground-floor-living-interior-designing-12-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Ground Floor Living Interior Designing 13 1024X555",
      "src": "/assets/images/interior/innovate-builders-ground-floor-living-interior-designing-13-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Ground Floor Living Interior Designing 14 1024X555",
      "src": "/assets/images/interior/innovate-builders-ground-floor-living-interior-designing-14-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Ground Floor Living Interior Designing 2 1024X555",
      "src": "/assets/images/interior/innovate-builders-ground-floor-living-interior-designing-2-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Ground Floor Living Interior Designing 3 1024X555",
      "src": "/assets/images/interior/innovate-builders-ground-floor-living-interior-designing-3-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Ground Floor Living Interior Designing 4 1024X555",
      "src": "/assets/images/interior/innovate-builders-ground-floor-living-interior-designing-4-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Ground Floor Living Interior Designing 5 1024X555",
      "src": "/assets/images/interior/innovate-builders-ground-floor-living-interior-designing-5-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Ground Floor Living Interior Designing 6 1024X555",
      "src": "/assets/images/interior/innovate-builders-ground-floor-living-interior-designing-6-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Ground Floor Living Interior Designing 7 1024X555",
      "src": "/assets/images/interior/innovate-builders-ground-floor-living-interior-designing-7-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Ground Floor Living Interior Designing 8 1024X555",
      "src": "/assets/images/interior/innovate-builders-ground-floor-living-interior-designing-8-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Ground Floor Living Interior Designing 9 1024X555",
      "src": "/assets/images/interior/innovate-builders-ground-floor-living-interior-designing-9-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Kids Room Interior Designing 1 1024X555",
      "src": "/assets/images/interior/innovate-builders-kids-room-interior-designing-1-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Kids Room Interior Designing 2 1024X555",
      "src": "/assets/images/interior/innovate-builders-kids-room-interior-designing-2-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Kitchen Interior Designing 1 1024X555",
      "src": "/assets/images/interior/innovate-builders-kitchen-interior-designing-1-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Kitchen Interior Designing 10 1024X555",
      "src": "/assets/images/interior/innovate-builders-kitchen-interior-designing-10-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Kitchen Interior Designing 11 1024X555",
      "src": "/assets/images/interior/innovate-builders-kitchen-interior-designing-11-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Kitchen Interior Designing 12 1024X555",
      "src": "/assets/images/interior/innovate-builders-kitchen-interior-designing-12-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Kitchen Interior Designing 2 1024X555",
      "src": "/assets/images/interior/innovate-builders-kitchen-interior-designing-2-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Kitchen Interior Designing 3 1024X555",
      "src": "/assets/images/interior/innovate-builders-kitchen-interior-designing-3-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Kitchen Interior Designing 4 1024X555",
      "src": "/assets/images/interior/innovate-builders-kitchen-interior-designing-4-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Kitchen Interior Designing 5 1024X555",
      "src": "/assets/images/interior/innovate-builders-kitchen-interior-designing-5-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Kitchen Interior Designing 6 1024X555",
      "src": "/assets/images/interior/innovate-builders-kitchen-interior-designing-6-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Kitchen Interior Designing 7 1024X555",
      "src": "/assets/images/interior/innovate-builders-kitchen-interior-designing-7-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Kitchen Interior Designing 8 1024X555",
      "src": "/assets/images/interior/innovate-builders-kitchen-interior-designing-8-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Kitchen Interior Designing 9 1024X555",
      "src": "/assets/images/interior/innovate-builders-kitchen-interior-designing-9-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Office Room Interior Designing 1 1024X555",
      "src": "/assets/images/interior/innovate-builders-office-room-interior-designing-1-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Wash Area Interior Designing 2 1024X555",
      "src": "/assets/images/interior/innovate-builders-wash-area-interior-designing-2-1024x555.jpg"
    },
    {
      "title": "Innovate Builders Wash Area Interior Designing 3 1024X555",
      "src": "/assets/images/interior/innovate-builders-wash-area-interior-designing-3-1024x555.jpg"
    }
  ]
};
